### ISSUE TITLE
Play only those audio which are currently shown at map

### ISSUE THREAD

**Issue by Bibiko** [cldf/cldfofflinebrowser#17]
For larger datasets showing languages world-wide

**Comment by xrotwang** [comment]
I don't think this is relevant. This tool is meant for the particular use case of fieldwork in remote locations, and thus does not need to be applicable to all sorts of CLDF datasets.

**Comment by xrotwang** [comment]
otoh, one could throw [this line](https://stackoverflow.com/a/35656174) into `offline.js` and have that feature implemented.
