### ISSUE TITLE
catch cases for blank language coordinates 

### ISSUE THREAD

**Issue by Bibiko** [cldf/cldfofflinebrowser#19]

**Comment by Bibiko** [comment]
@xrotwang What should be the policy here? Should we ignore all languages and their data if a given language has no geo coordinates? Or should we show the data (forms/lexemes) inside the data tables but no dot at the map?

**Comment by xrotwang** [comment]
I'd say ignore competely. This thing is about "putting voices on the map" after all, which requires coordinates.
