### ISSUE TITLE
On Chrome one cannot play the sound from popup

### ISSUE THREAD

**Issue by Bibiko** [cldf/cldfofflinebrowser#6]
<img width="213" alt="p2" src="https://user-images.githubusercontent.com/16273/98931386-3e360780-24de-11eb-91b6-5bb082b227e7.png">

**Comment by Bibiko** [comment]
if lexeme is too short

**Comment by Bibiko** [comment]
one could also think of a click event which shows to popup and plays the audio automatically

**Comment by xrotwang** [comment]
probably a min-width would do the trick.
